version: '3'
services:
  jenkis:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: jenkis
    build: .
    ports:
      - "50000:50000"
      - "8081:8080"
      - "5001:5001"
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
     - "./jenkins_home:/var/jenkins_home"
     - "/var/run/docker.sock:/var/run/docker.sock"